AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Builds serverless API, complete with Lambda functions,
  API Gateway, SQS Queues, DynamoDB table, and an S3 bucket.
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME: !Ref DemoTable
        SQS_QUEUE_URL: !Ref DemoQueue

    
    
  
  
  
  
  
  
  
  
Outputs:
  
  GetMessagesApi:
    Description: 'Example API Gateway endpoint: GetMessagesFunction'
    Value: !Sub "https://${DemoServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getMessages/"
